/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dategram;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author Keh Perick
 */
public class DateFrameViewer extends javax.swing.JFrame {

    /**
     * Creates new form DateFrameViewer
     */
    public DateFrameViewer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        countBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        daysLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        monthsLabel = new javax.swing.JLabel();
        yearsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jTextField2.setText(java.time.LocalDate.now().toString().replace("-", "/")
        );
        LocalDate today = LocalDate.now();
        String formatedDate = today.format(DateTimeFormatter.ofPattern("dd-MM-yyyy"));
        jTextField2.setText(formatedDate.replace("-", "/"));

        countBtn.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        countBtn.setText("count");
        countBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countValues(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Days");

        daysLabel.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        daysLabel.setText("00");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel3.setText("Months");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel4.setText("Years");

        monthsLabel.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        monthsLabel.setText("00");

        yearsLabel.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        yearsLabel.setText("00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(daysLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(countBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(monthsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(yearsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(countBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearsLabel)
                    .addComponent(daysLabel)
                    .addComponent(monthsLabel))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void countValues(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countValues
        int day, day1;
        int month, month1;
        int year = 0, year1 = 0;
        DataVerifier dataVerifier = null;
        DataVerifier dataVerifier1 = null;
        try {
            dataVerifier = new DataVerifier(jTextField1.getText());
            year = dataVerifier.getYear();
            try {
                    dataVerifier.validateMonth();
                    day = dataVerifier.getMonth();
                } catch (IllegalArgumentException e) {
                    displayError(e.getMessage());
                }
            try {
                dataVerifier.validateDay();
                day = dataVerifier.getDay();
                
            } catch (IllegalArgumentException e) {
                displayError(e.getMessage());
            }
            catch(ArrayIndexOutOfBoundsException aiob){
                displayError("month value has exceeded 12. Please kindly set a valid month [1-12]");
            }
            
        } catch (CPSC1181Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        
        
        
        try {
            dataVerifier1 = new DataVerifier(jTextField1.getText());
            year1 = dataVerifier1.getYear();
            try {
                    dataVerifier1.validateMonth();
                    year1 = dataVerifier1.getMonth();
                } catch (IllegalArgumentException e) {
                    displayError(e.getMessage());
                }
            try {
                dataVerifier1.validateDay();
                year1 = dataVerifier1.getDay();
            } catch (IllegalArgumentException e) {
                displayError(e.getMessage());
            }
            catch(ArrayIndexOutOfBoundsException aiob){
                displayError("month value has exceeded 12. Please kindly set a valid month [1-12]");
            }
            
        } catch (CPSC1181Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        
        
        
        DataCounterPanel counter= new DataCounterPanel(jTextField1.getText(), jTextField2.getText());
        try {
            counter.validateDifference(year, year1);
            daysLabel.setText(String.valueOf(counter.countDaysBetween()));
            monthsLabel.setText(String.valueOf(counter.countMonthsBetween()));
            yearsLabel.setText(String.valueOf(counter.countYearsBetween()));
        } catch (CPSC1181Exception e) {
            displayError(e.getMessage());
        }
        
       
        
    }//GEN-LAST:event_countValues

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DateFrameViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DateFrameViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DateFrameViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DateFrameViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DateFrameViewer().setVisible(true);
            }
        });
    }
    
    public void displayError(String message){
        JOptionPane.showMessageDialog(rootPane, message);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton countBtn;
    private javax.swing.JLabel daysLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel monthsLabel;
    private javax.swing.JLabel yearsLabel;
    // End of variables declaration//GEN-END:variables
}

